import { getTenantModels } from "@/lib/tenantDb";
/**
 * GET /api/cron/wa-daily-report
 * Send daily sales summary to the owner via WA.
 */
import { NextRequest, NextResponse } from 'next/server';



import { sendWhatsApp } from '@/lib/fonnte';

export async function GET(request: NextRequest, props: any) {
    const tenantSlug = request.headers.get('x-store-slug') || 'pusat';
    const { Invoice, Settings } = await getTenantModels(tenantSlug);

    try {
        const authHeader = request.headers.get('authorization');
        const cronSecret = process.env.CRON_SECRET;
        if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
            return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
        }

        
        

        const settings = await Settings.findOne();
        const ownerPhone = settings?.waOwnerNumber;
        const storeName = settings?.storeName || 'Salon';

        if (!ownerPhone) {
            return NextResponse.json({
                success: true,
                message: 'No owner WA number configured in settings',
                sent: 0,
            });
        }

        // Get today's date range
        const today = new Date();
        const startOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate());
        const endOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1);

        // Query today's paid invoices
        const invoices = await Invoice.find({
            date: { $gte: startOfDay, $lt: endOfDay },
            status: 'paid',
        }).lean();

        // Calculate totals
        const totalCustomers = new Set(invoices.map((inv: any) => String(inv.customer))).size;
        const totalRevenue = invoices.reduce((sum: number, inv: any) => sum + (inv.totalAmount || 0), 0);
        const totalTips = invoices.reduce((sum: number, inv: any) => sum + (inv.tips || 0), 0);

        // Payment method breakdown
        const paymentBreakdown: Record<string, number> = {};
        for (const inv of invoices) {
            const methods = (inv as any).paymentMethods;
            if (Array.isArray(methods) && methods.length > 0) {
                for (const pm of methods) {
                    const method = pm.method || 'Other';
                    paymentBreakdown[method] = (paymentBreakdown[method] || 0) + (pm.amount || 0);
                }
            } else {
                const method = (inv as any).paymentMethod || 'Cash';
                paymentBreakdown[method] = (paymentBreakdown[method] || 0) + ((inv as any).amountPaid || 0);
            }
        }

        // Format day name in Indonesian
        const dayNames = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'];
        const dayName = dayNames[today.getDay()];
        const dateStr = today.toLocaleDateString('id-ID', {
            day: 'numeric',
            month: 'long',
            year: 'numeric',
        });

        const fmt = (n: number) => `Rp${n.toLocaleString('id-ID')}`;

        // Build payment breakdown text
        const paymentLines = Object.entries(paymentBreakdown)
            .map(([method, amount]) => `• ${method}: ${fmt(amount)}`)
            .join('\n');

        const message =
            `📊 *Laporan Harian — ${storeName}*\n\n` +
            `📅 Hari *${dayName}*, ${dateStr}\n\n` +
            `👥 Total Customer Visit: *${totalCustomers} orang*\n` +
            `🧾 Total Transaksi: *${invoices.length}*\n\n` +
            `💰 *Rincian Pembayaran:*\n` +
            `${paymentLines || '• Belum ada transaksi'}\n\n` +
            `💵 Total Pendapatan: *${fmt(totalRevenue)}*\n` +
            (totalTips > 0 ? `💝 Total Tips: *${fmt(totalTips)}*\n` : '') +
            `\n— Generated by ${storeName} POS System`;

        const result = await sendWhatsApp(ownerPhone, message);

        return NextResponse.json({
            success: true,
            message: 'Daily report sent to owner',
            sent: result.success ? 1 : 0,
            report: {
                date: dateStr,
                totalCustomers,
                totalTransactions: invoices.length,
                totalRevenue,
                totalTips,
                paymentBreakdown,
            },
            error: result.error || undefined,
        });
    } catch (error: any) {
        console.error('WA daily report cron error:', error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
