import { getTenantModels } from "@/lib/tenantDb";
/**
 * GET /api/cron/wa-daily-report
 * Send daily sales summary to the owner via WA.
 */
import { NextRequest, NextResponse } from 'next/server';



import { decryptFonnteToken } from '@/lib/encryption';
import { sendWhatsApp } from '@/lib/fonnte';
import { hasRunToday, markAsRun } from '@/lib/cronDedup';
import { getCurrentDateInTimezone, getUtcRangeForDateRange } from '@/lib/dateUtils';

export async function GET(request: NextRequest, props: any) {
    const tenantSlug = request.headers.get('x-store-slug') || 'pusat';
    const { Invoice, Settings } = await getTenantModels(tenantSlug);

    try {
        const authHeader = request.headers.get('authorization');
        const cronSecret = process.env.CRON_SECRET;
        if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
            return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
        }

        
        

        const settings = await Settings.findOne();
        const ownerPhone = settings?.waOwnerNumber;
        const storeName = settings?.storeName || 'Salon';
        const fonnteToken = settings?.fonnteToken ? decryptFonnteToken(String(settings.fonnteToken).trim()) : undefined;

        // FLOW-04 FIX: Cek apakah scheduler sudah kirim daily report hari ini
        if (await hasRunToday('daily_report', tenantSlug)) {
            return NextResponse.json({
                success: true,
                message: 'Daily report already sent today (by scheduler or previous cron run)',
                sent: 0,
                skipped: true,
            });
        }

        if (!ownerPhone) {
            return NextResponse.json({
                success: true,
                message: 'No owner WA number configured in settings',
                sent: 0,
            });
        }

        // Get today's date range
        const tz = settings?.timezone || 'Asia/Jakarta';
        const todayStr = getCurrentDateInTimezone(tz);
        const { start: startOfDay, end: endOfDay } = getUtcRangeForDateRange(todayStr, todayStr, tz);

        // Query today's paid invoices
        const invoices = await Invoice.find({
            date: { $gte: startOfDay, $lt: endOfDay },
            status: 'paid',
        }).lean();

        // Calculate totals
        const totalCustomers = new Set(invoices.map((inv: any) => String(inv.customer))).size;
        const totalRevenue = invoices.reduce((sum: number, inv: any) => sum + (inv.totalAmount || 0), 0);
        const totalTips = invoices.reduce((sum: number, inv: any) => sum + (inv.tips || 0), 0);

        // Payment method breakdown
        const paymentBreakdown: Record<string, number> = {};
        for (const inv of invoices) {
            const methods = (inv as any).paymentMethods;
            if (Array.isArray(methods) && methods.length > 0) {
                for (const pm of methods) {
                    const method = pm.method || 'Other';
                    paymentBreakdown[method] = (paymentBreakdown[method] || 0) + (pm.amount || 0);
                }
            } else {
                const method = (inv as any).paymentMethod || 'Cash';
                paymentBreakdown[method] = (paymentBreakdown[method] || 0) + ((inv as any).amountPaid || 0);
            }
        }

        // Format day name in Indonesian based on timezone
        const now = new Date();
        const formatterDay = new Intl.DateTimeFormat('id-ID', { timeZone: tz, weekday: 'long' });
        const formatterDate = new Intl.DateTimeFormat('id-ID', {
            timeZone: tz,
            day: 'numeric',
            month: 'long',
            year: 'numeric',
        });
        const dayName = formatterDay.format(now);
        const dateStr = formatterDate.format(now);

        const fmt = (n: number) => `Rp${n.toLocaleString('id-ID')}`;

        // Build payment breakdown text
        const paymentLines = Object.entries(paymentBreakdown)
            .map(([method, amount]) => `• ${method}: ${fmt(amount)}`)
            .join('\n');

        const message =
            `📊 *Laporan Harian — ${storeName}*\n\n` +
            `📅 Hari *${dayName}*, ${dateStr}\n\n` +
            `👥 Total Customer Visit: *${totalCustomers} orang*\n` +
            `🧾 Total Transaksi: *${invoices.length}*\n\n` +
            `💰 *Rincian Pembayaran:*\n` +
            `${paymentLines || '• Belum ada transaksi'}\n\n` +
            `💵 Total Pendapatan: *${fmt(totalRevenue)}*\n` +
            (totalTips > 0 ? `💝 Total Tips: *${fmt(totalTips)}*\n` : '') +
            `\n— Generated by ${storeName} POS System`;

        const result = await sendWhatsApp(ownerPhone, message, fonnteToken);

        if (result.success) {
            await markAsRun('daily_report', tenantSlug, 'cron_route');
        }

        return NextResponse.json({
            success: true,
            message: 'Daily report sent to owner',
            sent: result.success ? 1 : 0,
            report: {
                date: dateStr,
                totalCustomers,
                totalTransactions: invoices.length,
                totalRevenue,
                totalTips,
                paymentBreakdown,
            },
            error: result.error || undefined,
        });
    } catch (error: any) {
        console.error('WA daily report cron error:', error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
